name: Build
on: [push]

jobs:
  win:
    runs-on: self-hosted
    name: Windows
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test MSYS2 Output
        shell: msys2 {0}
        run: |
          echo "MSYS2 is working!"
          uname -a
          which bash
          ls /
      - name: Install SDK
        id: install_sdk
        uses: WerWolv/imhex-download-sdk@v1.37.4
      - name: Build
        run: |
          mkdir build
          cd build
          IMHEX_SDK_PATH="${{ steps.install_sdk.outputs.sdk_path }}"      \
            cmake -G Ninja                                                \
            -DCMAKE_BUILD_TYPE=Release                                    \
            -DCMAKE_INSTALL_PREFIX="./install"                            \
            ..
          cmake --build .
          cmake --install .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/install
