name: Build
on: [push]

jobs:
  win:
    runs-on: self-hosted
    name: Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: ImHex Plugin
        id: install_sdk
        uses: WerWolv/imhex-download-sdk@v1.37.4
      - name: Build
        shell: cmd
        run: msys2 -c "mkdir build; cd build; IMHEX_SDK_PATH="${{ steps.install_sdk.outputs.sdk_path }}" \cmake -G Ninja \-DCMAKE_BUILD_TYPE=Release \-DCMAKE_INSTALL_PREFIX="./install" \..;cmake --build .; cmake --install ."
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/install
